# vim: sts=2 ts=2 sw=2 et ai

docker:
  process_signature: '/usr/bin/docker'
  python_pip_package: 'python-pip'
  install_docker_py: True
  refresh_repo: True
  config: []
  daemon:
    bip: "171.17.0.1/16"
    fixed-cidr: "172.17.0.0/16"
    hosts:
      - "fd://"
    tls: false
